"""Output adapters for delivering approved CFO memos.

After the Confirmation Gate approves a memo, it needs to actually go
somewhere — written to a file, sent via WhatsApp, emailed, etc. This
module defines the OutputAdapter Protocol and ships four concrete
implementations: console (default), file (markdown to disk), and stub
adapters for WhatsApp and email (log intent without sending).

The scheduler invokes the configured adapter for every APPROVED memo.
Rejected and revised memos do not flow through output adapters — only
explicitly approved content gets delivered.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Protocol

from multi_agent_cfo.intelligence.synthesis import SynthesisResult


class OutputAdapter(Protocol):
    """Protocol for delivering approved CFO memos.

    Implementations might write to disk, send via Slack/WhatsApp/email,
    POST to a webhook, or push to a queue. The scheduler doesn't care
    about the channel — it just calls deliver(synthesis) for every
    approved memo.
    """

    def deliver(self, synthesis: SynthesisResult) -> None: ...


class ConsoleOutputAdapter:
    """Default adapter: confirm to stdout that the memo would ship.

    The memo itself was already displayed during the Confirmation Gate,
    so there's no value in reprinting it. This adapter exists primarily
    as the default no-op for local dev — production use should pick
    a real channel.
    """

    def deliver(self, synthesis: SynthesisResult) -> None:
        company = synthesis.company
        print(f"  ✓ Delivered: memo for {company.ticker} ({company.name})")


class FileOutputAdapter:
    """Writes each approved memo to a timestamped markdown file.

    Files are written to a configurable output directory (default
    `./output/memos/`) and named `YYYY-MM-DD_TICKER.md`. Markdown was
    chosen over JSON because the primary consumer of delivered memos
    is a human stakeholder, not another system.
    """

    def __init__(self, output_dir: Path = Path("output/memos")) -> None:
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def deliver(self, synthesis: SynthesisResult) -> None:
        company = synthesis.company
        memo = synthesis.memo

        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        filename = self.output_dir / f"{date_str}_{company.ticker}.md"

        with filename.open("w", encoding="utf-8") as f:
            f.write(f"# CFO Memo: {company.name} ({company.ticker})\n\n")
            f.write(
                f"_Generated by `multi-agent-cfo` on {date_str} (UTC). "
                f"Model: {synthesis.model}. Tokens: "
                f"{synthesis.input_tokens} in, {synthesis.output_tokens} out._\n\n"
            )
            f.write("## Executive Summary\n\n")
            f.write(f"{memo.executive_summary}\n\n")
            f.write("## Financial Highlights\n\n")
            for item in memo.financial_highlights:
                f.write(f"- {item}\n")
            f.write("\n## Key Risks\n\n")
            for item in memo.key_risks:
                f.write(f"- {item}\n")
            f.write("\n## Recommended Actions\n\n")
            for item in memo.recommended_actions:
                f.write(f"- {item}\n")

        print(f"  ✓ Delivered: {filename}")


class WhatsAppOutputAdapter:
    """Stub WhatsApp adapter — logs intent but does not actually send.

    Real WhatsApp delivery requires Twilio, Meta's WhatsApp Business API,
    or a similar provider. This stub demonstrates the Protocol while
    keeping the project free of provider-specific credentials. Replace
    this implementation with one that calls your messaging provider's
    API; the Protocol interface stays identical.
    """

    def __init__(self, recipient: str = "+15555550100") -> None:
        self.recipient = recipient

    def deliver(self, synthesis: SynthesisResult) -> None:
        company = synthesis.company
        preview = synthesis.memo.executive_summary[:80] + "..."
        print(
            f"  ✓ [STUB] Would send via WhatsApp to {self.recipient}: "
            f"{company.ticker} memo — {preview!r}"
        )


class EmailOutputAdapter:
    """Stub email adapter — logs intent but does not actually send.

    Real email delivery requires SendGrid, Mailgun, AWS SES, or SMTP
    credentials. This stub demonstrates the Protocol while keeping the
    project free of provider-specific credentials.
    """

    def __init__(self, recipient: str = "stakeholder@example.com") -> None:
        self.recipient = recipient

    def deliver(self, synthesis: SynthesisResult) -> None:
        company = synthesis.company
        print(
            f"  ✓ [STUB] Would send via email to {self.recipient}: "
            f"CFO memo for {company.ticker} ({company.name})"
        )